backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
- name: "Blog"
  label: "Blog"
  folder: "src/pages/blog"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Description", name: "description", widget: "text"}
    - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
    - {label: "Featured Image", name: "featuredimage", widget: image}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list"}      
- name: "Atlas"
  label: "Atlas"
  folder: "src/pages/atlas"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Description", name: "description", widget: "text"}
    - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
    - {label: "Featured Image", name: "featuredimage", widget: image}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list"}
    - {label: "Location", name: "location", widget: "map" }


- name: "pages"
  label: "Pages"
  files:
    - file: "src/pages/index.md"
      label: "Landing Page"
      name: "index"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
        - {label: Title, name: title, widget: string}
        - {label: Image, name: image, widget: image}
        - {label: Tagline, name: tagline, widget: string}        
        - {label: Description, name: description, widget: string}
        - {label: Intro paragraphs, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Paragraph 1, name: text1, widget: text},{label: Paragraph 2, name: text2, widget: text},{label: Link text, name: linkText, widget: text},{label: Link url, name: linkUrl, widget: text}]}]}        
        - {label: "Body", name: "body", widget: "markdown"}
    - file: "src/pages/about/index.md"
      label: "About"
      name: "about"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
        - {label: Title, name: title, widget: string}
        - {label: Image, name: image, widget: image}
        - {label: Tagline, name: tagline, widget: string}        
        - {label: Description, name: description, widget: string}
        - {label: Partners, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Paragraph 1, name: text1, widget: text},{label: Paragraph 2, name: text2, widget: text},{label: Link text, name: linkText, widget: text},{label: Link url, name: linkUrl, widget: text}]}]}                
        - {label: "Body", name: "body", widget: "markdown"}
    - file: "src/pages/outputs/index.md"
      label: "Outputs"
      name: "outputs"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "outputs-page"}
        - {label: Title, name: title, widget: string}
        - {label: Image, name: image, widget: image}
        - {label: Tagline, name: tagline, widget: string}        
        - {label: Description, name: description, widget: string}
        - {label: Partners, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Paragraph 1, name: text1, widget: text},{label: Paragraph 2, name: text2, widget: text},{label: Link text, name: linkText, widget: text},{label: Link url, name: linkUrl, widget: text}]}]}                
        - {label: "Body", name: "body", widget: "markdown"}