backend:
  name: git-gateway
  branch: master

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

media_folder: static/img
public_folder: /img

collections:
- name: "Partners"
  label: "partners"
  folder: "src/pages/partners"
  create: true
  slug: "{{slug}}.{{language}}"
  fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "partner-post"}
    - {label: "Language", name: "language", widget: "string"}
    - {label: "Title", name: "title", widget: "string"}    
    - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
    - {label: "Featured Image", name: "featuredimage", widget: image}
    - {label: "Body", name: "body", widget: "markdown"}    

- name: "Atlases"
  label: "atlases"
  folder: "src/pages/atlases"
  create: true
  slug: "{{slug}}.{{language}}"
  fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "atlas-post"}
    - {label: "Language", name: "language", widget: "string"}
    - {label: "Title", name: "title", widget: "string"}    
    - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
    - {label: "Featured Image", name: "featuredimage", widget: image}
    - {label: "Body", name: "body", widget: "markdown"}    

- name: "Tools"
  label: "tools"
  folder: "src/pages/tools"
  create: true
  slug: "{{slug}}.{{language}}"
  fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tool-post"}
    - {label: "Language", name: "language", widget: "string"}
    - {label: "Title", name: "title", widget: "string"}    
    - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
    - {label: "Featured Image", name: "featuredimage", widget: image}
    - {label: "Body", name: "body", widget: "markdown"}    


    